// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBpDBBPD_SKsi1oflc20DvuhCHleij_Xw',
    appId: '1:536388308588:web:4a892f914d148f4c315249',
    messagingSenderId: '536388308588',
    projectId: 'ch-community-app',
    authDomain: 'ch-community-app.firebaseapp.com',
    storageBucket: 'ch-community-app.firebasestorage.app',
    measurementId: 'G-Y4R36FGVKN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkxg8jTYeFw29IoqZeDJ45VqZs7VK4Q5M',
    appId: '1:536388308588:android:790740b261ed9cce315249',
    messagingSenderId: '536388308588',
    projectId: 'ch-community-app',
    storageBucket: 'ch-community-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHJProF7c7PGnLlNta0mnut2BzKuylXaU',
    appId: '1:536388308588:ios:cc042ecc72f7148d315249',
    messagingSenderId: '536388308588',
    projectId: 'ch-community-app',
    storageBucket: 'ch-community-app.firebasestorage.app',
    androidClientId:
        '536388308588-24o23th7iagj8c14nct1ac6k5du1cgqa.apps.googleusercontent.com',
    iosClientId:
        '536388308588-t590t54d5uaajo3g2sog9mmmrt9o7pla.apps.googleusercontent.com',
    iosBundleId: 'com.codroidhub.adminApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHJProF7c7PGnLlNta0mnut2BzKuylXaU',
    appId: '1:536388308588:ios:cc042ecc72f7148d315249',
    messagingSenderId: '536388308588',
    projectId: 'ch-community-app',
    storageBucket: 'ch-community-app.firebasestorage.app',
    androidClientId:
        '536388308588-24o23th7iagj8c14nct1ac6k5du1cgqa.apps.googleusercontent.com',
    iosClientId:
        '536388308588-t590t54d5uaajo3g2sog9mmmrt9o7pla.apps.googleusercontent.com',
    iosBundleId: 'com.codroidhub.adminApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBpDBBPD_SKsi1oflc20DvuhCHleij_Xw',
    appId: '1:536388308588:web:be9ec89c0f5b9543315249',
    messagingSenderId: '536388308588',
    projectId: 'ch-community-app',
    authDomain: 'ch-community-app.firebaseapp.com',
    storageBucket: 'ch-community-app.firebasestorage.app',
    measurementId: 'G-BY2WV1ZV6R',
  );
}
